Ran pre-commit, added licenses
adafruit/Adafruit_CircuitPython_ImageLoad pull request #43
Opened 2021-02-04 19:54 UTC by dherrada

2021-02-10 14:22 UTC, FoamyGuy requested changes

2021-02-10 14:22 UTC, FoamyGuy commented on adafruit_imageload/pnm/__init__.py
> +# SPDX-FileCopyrightText: 2018 Scott Shawcroft for Adafruit Industries
In this file, and some others there are more authors listed below. I'll work on pushing these changes and wrapping this one up later tonight.

2021-02-10 20:59 UTC, dherrada commented
@FoamyGuy Thanks for noticing that!

2021-02-11 02:14 UTC, FoamyGuy approved these changes

2021-02-11 02:14 UTC, merged